Team1/Models/EFModels/HotelRoom.cs
namespace Team1.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class HotelRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelRoom()
        {
            HotelOrderItems = new HashSet<HotelOrderItem>();
            HotelRoomImages = new HashSet<HotelRoomImage>();
            PackageHotelRoomItems = new HashSet<PackageHotelRoomItem>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        public int HotelId { get; set; }

        [Required]
        [StringLength(50)]
        public string Size { get; set; }

        [Required]
        public string RoomFacilities { get; set; }

        public int Capacity { get; set; }

        public int BedCapacity { get; set; }

        [Required]
        public string MainImage { get; set; }

        public int WeekdayPrice { get; set; }

        public int WeekendPrice { get; set; }

        public int AddTimeFee { get; set; }

        public int Count { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelOrderItem> HotelOrderItems { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelRoomImage> HotelRoomImages { get; set; }

        public virtual Hotel Hotel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageHotelRoomItem> PackageHotelRoomItems { get; set; }
    }
}

Team1/Controllers/HotelRoomController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Team1.Models.EFModels;
using Team1.Models.Infra;

namespace Team1.Controllers
{
    public class HotelRoomController : Controller
    {
        private AppDbContext db = new AppDbContext();
        // GET: HotelRoom
        public ActionResult Index(int? id)
        {
            // 使用 LINQ 查询来找出所有匹配 hotelId 的 HotelRooms
            var hotelRooms = db.HotelRooms.Where(h => h.HotelId == id).ToList();
            ViewBag.hotelId = id;

            return View(hotelRooms);
        }

        // GET: HotelRooms/Create
        public ActionResult Create(int? id)
        {
            if (id.HasValue)
            {
                ViewBag.HotelId = new SelectList(db.Hotels, "Id", "Name", id.HasValue ? id.Value : -1);
                ViewBag.SelectedHotelId = id.HasValue ? id.Value : -1; // 确保有默认值或合理的备选值
                ViewBag.SelectedHotelId = id; // 用于在视图中设置隐藏字段的值
            }
            else
            {
                ViewBag.HotelId = new SelectList(db.Hotels, "Id", "Name");
            }
            return View();
        }

        // POST: HotelRooms/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,HotelId,Size,RoomFacilities,Capacity,BedCapacity,MainImage,WeekdayPrice,WeekendPrice,AddTimeFee,Count")] HotelRoom hotelRoom, HttpPostedFileBase file1)
        {
            if (ModelState.IsValid)
            {
                hotelRoom.RoomFacilities = "1"; //沒見到資料表 先都預設為1 之後再看是否使用
                //上傳圖片檔案
                string path = Server.MapPath("/Uploads");
                string newFileName = new UploadFileHelper().UploadFile(file1, path);
                hotelRoom.MainImage = "../" + newFileName;
                db.HotelRooms.Add(hotelRoom);
                db.SaveChanges();
                return RedirectToAction("Index","Hotel");
            }

            ViewBag.HotelId = new SelectList(db.Hotels, "Id", "Name", hotelRoom.HotelId);
            return View(hotelRoom);
        }

        // GET: HotelRooms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelRoom hotelRoom = db.HotelRooms.Find(id);
            if (hotelRoom == null)
            {
                return HttpNotFound();
            }
            ViewBag.HotelId = id;
            return View(hotelRoom);
        }

        // POST: HotelRooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HotelRoom hotelRoom = db.HotelRooms.Find(id);
            // 假设HotelRoom模型中有一个名为HotelId的属性，指向Hotel的外键
            int hotelId = hotelRoom.HotelId;
            db.HotelRooms.Remove(hotelRoom);
            db.SaveChanges();
            // 使用hotelId作为参数重定向到Index视图
            return RedirectToAction("Index", new { id = hotelId });
        }

        // GET: HotelRooms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelRoom hotelRoom = db.HotelRooms.Find(id);
            if (hotelRoom == null)
            {
                return HttpNotFound();
            }
            ViewBag.HotelId = new SelectList(db.Hotels, "Id", "Name", hotelRoom.HotelId);
            ViewBag.SelectedHotelId = id.HasValue ? id.Value : -1; // 确保有默认值或合理的备选值
            ViewBag.SelectedHotelId = id; // 用于在视图中设置隐藏字段的值
            return View(hotelRoom);
        }

        // POST: HotelRooms/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,HotelId,Size,RoomFacilities,Capacity,BedCapacity,MainImage,WeekdayPrice,WeekendPrice,AddTimeFee,Count")] HotelRoom hotelRoom, HttpPostedFileBase file1)
        {
            if (ModelState.IsValid)
            {
                if (file1 != null && file1.ContentLength > 0)
                {
                    string path = Server.MapPath("/Uploads");
                    string newFileName = new UploadFileHelper().UploadFile(file1, path);
                    // 更新Hotel对象的MainImage属性
                    hotelRoom.MainImage = "../" + newFileName;
                }
                hotelRoom.RoomFacilities = "1"; //忘記建資料表 先預設
                db.Entry(hotelRoom).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = hotelRoom.HotelId });
            }
            ViewBag.HotelId = new SelectList(db.Hotels, "Id", "Name", hotelRoom.HotelId);
            return View(hotelRoom);
        }

    }
}

Team1/Views/HotelRoom/Create.cshtml
@model Team1.Models.EFModels.HotelRoom

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "HotelRoom", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>HotelRoom</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HotelId, "HotelId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("HotelId", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
            @Html.Hidden("HotelId", (object)ViewBag.SelectedHotelId)
            @Html.ValidationMessageFor(model => model.HotelId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.RoomFacilities, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomFacilities, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomFacilities, "", new { @class = "text-danger" })
            </div>
        </div>
    *@

    <div class="form-group">
        @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BedCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BedCapacity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BedCapacity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MainImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*Html.EditorFor(model => model.MainImage, new { htmlAttributes = new { @class = "form-control" } })*@
            <input class="form-control" type="file" name="file1" id="file1">
            @Html.ValidationMessageFor(model => model.MainImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.WeekdayPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.WeekdayPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.WeekdayPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.WeekendPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.WeekendPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.WeekendPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AddTimeFee, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddTimeFee, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AddTimeFee, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = ViewBag.SelectedHotelId },null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Team1/Views/HotelRoom/Delete.cshtml
@model Team1.Models.EFModels.HotelRoom

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HotelRoom</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hotel.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hotel.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomFacilities)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomFacilities)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BedCapacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BedCapacity)
        </dd>

        <dt>
            <img src="@Model.MainImage" alt="Hotel Image" style="width:100px; height:auto;" />
        </dt>

        @*<dd>
            @Html.DisplayFor(model => model.MainImage)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.WeekdayPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WeekdayPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WeekendPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WeekendPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddTimeFee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddTimeFee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Count)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { id = ViewBag.HotelId })
        </div>
    }
</div>

Team1/Views/HotelRoom/Edit.cshtml
@model Team1.Models.EFModels.HotelRoom

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "HotelRoom", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HotelRoom</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HotelId, "HotelId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HotelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HotelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        @*@<div class="form-group">
            @Html.LabelFor(model => model.RoomFacilities, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomFacilities, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomFacilities, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BedCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BedCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BedCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MainImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.MainImage, new { htmlAttributes = new { @class = "form-control" } })
                <input class="form-control" type="file" name="file1" id="file2">
                @Html.ValidationMessageFor(model => model.MainImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WeekdayPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WeekdayPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WeekdayPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WeekendPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WeekendPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WeekendPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddTimeFee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddTimeFee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddTimeFee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = ViewBag.SelectedHotelId }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Team1/Views/HotelRoom/Index.cshtml
@model IEnumerable<Team1.Models.EFModels.HotelRoom>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { id = ViewBag.hotelId })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Hotel.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Size)
        </th>
        @*<th>
                @Html.HiddenFor(model => model.RoomFacilities)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Capacity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BedCapacity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MainImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WeekdayPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WeekendPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddTimeFee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Hotel.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.RoomFacilities)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Capacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BedCapacity)
            </td>
            <td>
                <img src="@item.MainImage" alt="HotelRoom Image" style="width:200px; height:auto;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WeekdayPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WeekendPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddTimeFee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Count)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @*Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>
<div>
    @Html.ActionLink("Back to List", "Index", "Hotel")
</div>