Team1/Controllers/HotelController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Team1.Models;
using Team1.Models.EFModels;
using Team1.Models.Infra;

namespace Team1.Controllers
{
    public class Facilities
    {
        public List<int> FacilityIds { get; set; }

    }


    public class HotelController : Controller
    {
        private AppDbContext db = new AppDbContext();
        // GET: Hotel
        public ActionResult Index(string searchString, string district, decimal? minPrice, decimal? maxPrice)
        {
            var data = db.Hotels.ToList();
            var hotelCategories = db.HotelCategories.ToList();

            var hotels = from m in db.Hotels
                         select m;

            // 按酒店名称搜索
            if (!String.IsNullOrEmpty(searchString))
            {
                hotels = hotels.Where(s => s.Name.Contains(searchString));
            }

            // 按地区搜索
            if (!String.IsNullOrEmpty(district))
            {
                hotels = hotels.Where(s => s.District.Name.Contains(district));
            }


            foreach (var singleData in data)
            {
                if (string.IsNullOrEmpty(singleData.HotelFacilities))
                {
                    continue;
                }

                Facilities obj = JsonConvert.DeserializeObject<Facilities>(singleData.HotelFacilities);
                string detail = "<ul>";

                if (obj?.FacilityIds != null)
                {
                    foreach (var facilityId in obj.FacilityIds)
                    {
                        var facility = hotelCategories.FirstOrDefault(x => x.Id == facilityId);
                        if (facility != null)
                        {
                            detail += $"<li>{facility.JAON}</li>";
                        }
                    }
                }
                detail += "</ul>";
                singleData.HotelFacilities = detail;
            }

            return View(hotels.ToList());
        }

        // GET: Hotel/Create
        public ActionResult Create()
        {
            Hotel hotel = new Hotel();
            var hotelCategories = db.HotelCategories.ToList();
            ViewBag.DistrictId = new SelectList(db.Districts, "Id", "Name");
            ViewBag.HotelTypeId = new SelectList(db.HotelTypes, "Id", "Name");
            ViewBag.Categories = hotelCategories;
            return View(hotel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,DistrictId,Address,Grade,Phone,Level,MainImage,CheckinStart,CheckinEnd,CheckoutStart,CheckoutEnd,AddBedFee,BreakfastPrice,HotelTypeId,HotelFacilities,Email")] Hotel hotel, int[] SelectedCategories, HttpPostedFileBase file1)
        {
            if (ModelState.IsValid)
            {
                // 序列化成 JSON 格式
                //string json = JsonConvert.SerializeObject(new { FacilityIds = hotel.SelectedCategoryIds });
                // 序列化成 JSON 格式
                var facilitiesJson = JsonConvert.SerializeObject(new { FacilityIds = SelectedCategories });

                //上傳圖片檔案
                string path = Server.MapPath("/Uploads");
                string newFileName = new UploadFileHelper().UploadFile(file1, path);
                hotel.MainImage = newFileName;

                // 指定給 HotelFacilities 欄位
                //hotel.HotelFacilities = JsonConvert.SerializeObject(new { FacilityIds = new int[] { 1, 2, 9, 11 } });
                hotel.HotelFacilities = facilitiesJson;
                db.Hotels.Add(hotel);
                db.SaveChanges();
                Session["HotelId"] = hotel.Id;
                return RedirectToAction("index");
            }

            ViewBag.DistrictId = new SelectList(db.Districts, "Id", "Name", hotel.DistrictId);
            ViewBag.HotelTypeId = new SelectList(db.HotelTypes, "Id", "Name", hotel.HotelTypeId);
            ViewBag.Categories = db.HotelCategories.ToList();  // 重新設置類別
            return View(hotel);
        }
        public ActionResult CreateRoom()
        {
            var hotelId = Session["HotelId"] as int?;
            if (hotelId == null)
            {
                return RedirectToAction("index");
            }

            var model = new HotelRoom { HotelId = hotelId.Value };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRoom(HotelRoom hotelRoom)
        {
            if (ModelState.IsValid)
            {
                db.HotelRooms.Add(hotelRoom);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hotelRoom);
        }

        // GET: Hotel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }

            var data = hotel.HotelFacilities;
            Facilities obj = JsonConvert.DeserializeObject<Facilities>(data);
            string detail = "<ul>";

            foreach (var facilityId in obj.FacilityIds)
            {
                var facility = db.HotelCategories.FirstOrDefault(x => x.Id == facilityId);
                if (facility != null)
                {
                    detail += $"<li>{facility.JAON}</li>";
                }
            }
            detail += "</ul>";
            hotel.MainImage = "../" + hotel.MainImage;

            // 將設施細節存儲在 ViewBag 中，以便在視圖中顯示
            ViewBag.FacilityDetails = detail;

            return View(hotel);

        }

        // POST: Hotel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hotel hotel = db.Hotels.Find(id);
            db.Hotels.Remove(hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public JsonResult GetFacilities()
        {
            var facilities = db.HotelCategories
                .Select(e => e.JAON)
                .Distinct()
                .ToList();

            return Json(facilities, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }

            // 解析 JSON 字符串以获取 FacilityIds
            var facilitiesData = JsonConvert.DeserializeObject<dynamic>(hotel.HotelFacilities);
            int[] facilityIds = facilitiesData.FacilityIds.ToObject<int[]>();

            // 获取所有可能的设施，以便在视图中显示
            var allFacilities = db.HotelCategories.ToList();

            // 将数据发送到视图
            ViewBag.SelectedFacilityIds = new HashSet<int>(facilityIds);
            ViewBag.AllFacilities = allFacilities;
            ViewBag.DistrictId = new SelectList(db.Districts, "Id", "Name", hotel.DistrictId);
            ViewBag.HotelTypeId = new SelectList(db.HotelTypes, "Id", "Name", hotel.HotelTypeId);
            return View(hotel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,DistrictId,Address,Grade,Phone,Level,MainImage,CheckinStart,CheckinEnd,CheckoutStart,CheckoutEnd,AddBedFee,BreakfastPrice,HotelTypeId,HotelFacilities,Email")] Hotel hotel, int[] selectedFacilityIds, HttpPostedFileBase file1)
        {
            if (ModelState.IsValid)
            {
                if (file1 != null && file1.ContentLength > 0)
                {
                    string path = Server.MapPath("/Uploads");
                    string newFileName = new UploadFileHelper().UploadFile(file1, path);
                    // 更新Hotel对象的MainImage属性
                    hotel.MainImage = newFileName;
                }

                db.Entry(hotel).State = EntityState.Modified;
                // 更新 HotelFacilities 字段
                var jsonFacilities = JsonConvert.SerializeObject(new { FacilityIds = selectedFacilityIds });
                hotel.HotelFacilities = jsonFacilities;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DistrictId = new SelectList(db.Districts, "Id", "Name", hotel.DistrictId);
            ViewBag.HotelTypeId = new SelectList(db.HotelTypes, "Id", "Name", hotel.HotelTypeId);
            return View(hotel);
        }
    }
}

Team1/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Team1.Models;
using Team1.Models.EFModels;

namespace Team1.Controllers
{
    
    public class OrderController : Controller
    {
        private AppDbContext db = new AppDbContext();
        // GET: Order
        public ActionResult Index()
        {
            var data = db.HotelOrders;
            return View(data);
        }
        public ActionResult Create()
        {
            ViewBag.AdminId = new SelectList(db.BEAdmins, "Id", "Account");
            ViewBag.HotelOrderCancelReasonId = new SelectList(db.HotelOrderCancelReasons, "Id", "Name");
            ViewBag.HotelOrderStatusId = new SelectList(db.HotelOrderStatuses, "Id", "Name");
            ViewBag.MemberId = new SelectList(db.Members, "Id", "Account");
            return View();
        }

        // POST: Orders/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,OrderSn,NumberOfPeople,Breakfast,HotelOrderStatusId,Phone,CreditCard,MemberId,Price,Checkin,Checkout,HotelOrderCancelReasonId,AdminId")] HotelOrder hotelOrder)
        {
            if (ModelState.IsValid)
            {
                db.HotelOrders.Add(hotelOrder);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AdminId = new SelectList(db.BEAdmins, "Id", "Account", hotelOrder.AdminId);
            ViewBag.HotelOrderCancelReasonId = new SelectList(db.HotelOrderCancelReasons, "Id", "Name", hotelOrder.HotelOrderCancelReasonId);
            ViewBag.HotelOrderStatusId = new SelectList(db.HotelOrderStatuses, "Id", "Name", hotelOrder.HotelOrderStatusId);
            ViewBag.MemberId = new SelectList(db.Members, "Id", "Account", hotelOrder.MemberId);
            return View(hotelOrder);
        }

    }
}

Team1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh-tw">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
	@*@Styles.Render("~/Content/css")
		@Scripts.Render("~/bundles/modernizr")*@
	<script src="https://unpkg.com/&#64tabler/core@1.0.0-beta3/dist/js/tabler.min.js"></script>
	<link rel="stylesheet" href="https://unpkg.com/&#64tabler/core@1.0.0-beta3/dist/css/tabler.min.css">
	<link rel="stylesheet" href="https://unpkg.com/&#64@tabler/core@1.0.0-beta3/dist/css/tabler-flags.min.css">
	<link rel="stylesheet" href="https://unpkg.com/&#64tabler/core@1.0.0-beta3/dist/css/tabler-payments.min.css">
	<link rel="stylesheet" href="https://unpkg.com/&#64tabler/core@1.0.0-beta3/dist/css/tabler-vendors.min.css">
</head>
<body>
	<div class="page">
		<!-- Sidebar -->
		<aside class="navbar navbar-vertical navbar-expand-sm navbar-dark">
			<div class="container-fluid">
				<button class="navbar-toggler" type="button">
					<span class="navbar-toggler-icon"></span>
				</button>
				<h1 class="navbar-brand navbar-brand-autodark">
					<a href="href=" @Url.Action("Index", "Home") "">
						<!-- <img src="https://preview.tabler.io/static/logo-white.svg" width="110" height="32" alt="Tabler"
						  class="navbar-brand-image"> -->
						<h1 class="navbar-brand-text fw-bold">TravelPlatform</h1>
					</a>
				</h1>
				<div class="collapse navbar-collapse" id="sidebar-menu">
                    <ul class="navbar-nav pt-lg-3">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Home")">
                                <span class="nav-link-title">
                                    首頁
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("About", "Home")">
                                <span class="nav-link-title">
                                    關於
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Contact", "Home")">
                                <span class="nav-link-title">
                                    連絡人
                                </span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="#連結放這裡( 用這個-@Url.Action("Contact", "Home"))">
                                <span class="nav-link-title">
                                    Link 3
                                </span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="#連結放這裡( 用這個-@Url.Action("Contact", "Home"))">
                                <span class="nav-link-title">
                                    Link 3
                                </span>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class=" nav-link dropdown-toggle" data-bs-toggle="dropdown">訂單管理</a>
                            <div class="dropdown-menu ">
                                <a class="dropdown-item" href="@Url.Action("Index", "Order")">飯店訂單</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class=" nav-link dropdown-toggle" data-bs-toggle="dropdown">飯店管理</a>
                            <div class="dropdown-menu ">
                                <a class="dropdown-item" href="@Url.Action("Index", "Hotel")">飯店</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a href="#" class=" nav-link dropdown-toggle" data-bs-toggle="dropdown">管理員</a>
                            <div class="dropdown-menu ">
                                <a class="dropdown-item" href="@Url.Action("Index", "Admins")">管理員首頁</a>
                                <a class="dropdown-item" href="#">新增管理員</a>
                                <a class="dropdown-item" href="#">設定管理員角色</a>
                                <a class="dropdown-item" href="#">新增角色</a>
                                <a class="dropdown-item" href="#">設定角色權限</a>
                            </div>
                        </li>
                    </ul>
				</div>
			</div>
		</aside>
		<header class="navbar navbar-expand-sm navbar-light d-print-none">
			<div class="container-xl">
				<h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
					<a href="href=" @Url.Action("Index", "Home") "">
						<!-- <img src="https://preview.tabler.io/static/logo.svg" width="110" height="32" alt="Tabler"
						  class="navbar-brand-image" /> -->
						<h1 class="navbar-brand-text fw-bold">TravelPlatform</h1>
					</a>
				</h1>

				<div class="navbar-nav flex-row order-md-last">
					<div class="nav-item">
						<a href="#" class="nav-link d-flex lh-1 text-reset p-0">
							<span class="avatar avatar-sm" style="background-image: url(/samples/avatars/002m.jpg)"></span>
							<div class="d-none d-xl-block ps-2">
								<div>管理員帳號</div>
								<div class="mt-1 small text-secondary">管理員姓名</div>
							</div>
						</a>
					</div>
				</div>
			</div>
		</header>
		<div class="page-wrapper">
			<div class="page-body">
				<div class="container-xl">
					@RenderBody()
					<hr />
					<footer>
						<p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
					</footer>
				</div>
			</div>
		</div>
	</div>


	@*@Scripts.Render("~/bundles/jquery")
		@Scripts.Render("~/bundles/bootstrap")*@
	@RenderSection("scripts", required: false)
</body>
</html>