Team1/Models/EFModels/Package.cs
namespace Team1.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            PackageAttractionItems = new HashSet<PackageAttractionItem>();
            PackageHotelRoomItems = new HashSet<PackageHotelRoomItem>();
            PackageMemos = new HashSet<PackageMemo>();
            PackageOrdes = new HashSet<PackageOrde>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        public int Price { get; set; }

        public int LowestGo { get; set; }

        public DateTime ApplyEndDate { get; set; }

        public DateTime ApplyBeginDate { get; set; }

        public int CanSold { get; set; }

        public int TotalNum { get; set; }

        [Required]
        [StringLength(50)]
        public string Image { get; set; }

        [Required]
        [StringLength(50)]
        public string Description { get; set; }

        [StringLength(50)]
        public string Alert { get; set; }

        public string PriceDescription { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageAttractionItem> PackageAttractionItems { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageHotelRoomItem> PackageHotelRoomItems { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageMemo> PackageMemos { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageOrde> PackageOrdes { get; set; }
    }
}

Team1/Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Metadata.Edm;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using System.Web.UI.WebControls;
using Team1.Models.EFModels;
using Team1.Scripts;
using Team1.ViewModels;

namespace Team1.Controllers
{
    public class PackageController : Controller
    {
        private AppDbContext db = new AppDbContext();
        PackgeService service = new PackgeService();

        // GET: Package
        public ActionResult Index(int? packageId = 0)
        {
            List<PackageVM> packageVM = service.Search(packageId).ToList();
            return View(packageVM);
        }

        // GET: Package/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Package/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price,LowestGo,ApplyEndDate,ApplyBeginDate,CanSold,TotalNum,Image,Description,Alert,PriceDescription")] PackageVM packageVM, HttpPostedFileBase ImageFile, HttpPostedFileBase DescriptionFile)
        {
            if (ModelState.IsValid)
            {
                if (packageVM.ApplyEndDate <= packageVM.ApplyBeginDate)
                {
                    // 如果 RoomId 已存在，添加錯誤信息到 ModelState
                    ModelState.AddModelError("ApplyEndDate", "報名截止日需大於報名開始日");
                    // 返回 View，讓使用者重新輸入
                    return View(packageVM);
                }
                packageVM.Image = SaveFile(ImageFile, "Image");
                packageVM.Description = SaveFile(DescriptionFile, "PackageDescription");
                service.Create(packageVM);
                return RedirectToAction("Index");
            }
            return View();
        }
        public string SaveFile(HttpPostedFileBase file,string type)
        {
            if (file != null && file.ContentLength > 0)
            {
                // 取得文件名
                string uploadFileName = Path.GetFileName(file.FileName);
                //取得副檔名
                string fileExtension = Path.GetExtension(uploadFileName);
                //存檔文件名
                string fileName = DateTime.Now.ToString("yyyyMMddHHmmss") + fileExtension;
                // 將文件保存到伺服器
                string filePath = Path.Combine(Server.MapPath("~/File/Pinyue/" + type), fileName);
                file.SaveAs(filePath);
                return fileName;
            }
            return null;
        }
        // GET: Package/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PackageVM data = service.Search(id).FirstOrDefault();
            if (data == null)
            {
                return HttpNotFound();
            }
            return View(data);
        }

        // POST: Package/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price,LowestGo,ApplyEndDate,ApplyBeginDate,CanSold,TotalNum,Image,Description,Alert,PriceDescription")] PackageVM packageVM, HttpPostedFileBase ImageFile, HttpPostedFileBase DescriptionFile)
        {
            if (ModelState.IsValid)
            {
                if (packageVM.ApplyEndDate <= packageVM.ApplyBeginDate)
                {
                    // 如果 RoomId 已存在，添加錯誤信息到 ModelState
                    ModelState.AddModelError("ApplyEndDate", "報名截止日需大於報名開始日");
                    // 返回 View，讓使用者重新輸入
                    return View(packageVM);
                }
                packageVM.Image = SaveFile(ImageFile, "Image");
                packageVM.Description = SaveFile(DescriptionFile, "PackageDescription");
                service.Edit(packageVM);
                return RedirectToAction("Index");
            }
            return View(packageVM);
        }

        // POST: Package/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // 先取得要刪除的房型
            var package = service.Search(id).FirstOrDefault();

            // 確保找到資料
            if (package != null)
            { 
                // 獲取圖檔路徑
                string[] path = { Server.MapPath(package.Image), Server.MapPath(package.Description) };
                foreach (var item in path)
                {
                    // 刪除圖檔
                    if (System.IO.File.Exists(item))
                    {
                        System.IO.File.Delete(item);
                    }
                }
                // 刪除
                service.Delete(id);
                // 返回到Index頁面或其他適當的頁面
                return RedirectToAction("Index");
            }
            else
            {
                // 如果找不到房型，返回一個錯誤視圖或其他處理方式
                return HttpNotFound();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(int? id, string name, DateTime? date)
        {
            // 在這裡獲取查詢參數，執行您的查詢邏輯
            // 使用 roomTypeId, typeName, capacity 進行過濾

            // 示例：您可能有一個服務類別（service），它可以處理查詢邏輯
            var result = service.Search_Cond(id, name, date);

            // 返回查詢結果，或者進行其他適當的處理
            return View("Index", result);
        }
    }
}

Team1/Views/Package/Create.cshtml
@model Team1.ViewModels.PackageVM

@{
	ViewBag.Title = "Create";
}

<style>
	h2 {
		background-color: powderblue;
		padding: 10px;
	}

	.form-horizontal {
		width: 80%;
		margin: auto;
	}

	.control-label {
		font-weight: bold;
	}

	.form-group {
		margin-bottom: 15px;
	}

	.col-md-offset-2 {
		margin-left: 16.66666667%;
	}

	.btn {
		margin-top: 15px;
	}

	#imagePreview {
		max-width: 100%;
		max-height: 200px;
		margin-top: 10px;
	}

	.form-group {
		width: 500px
	}
</style>

<h2>產品設定-新增</h2>

@using (Html.BeginForm("Create", "Package", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return validateFileSelect();" }))
{
	@Html.AntiForgeryToken()

<div class="form-horizontal">
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
			@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.LowestGo, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.LowestGo, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "1" } })
			@Html.ValidationMessageFor(model => model.LowestGo, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.ApplyBeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.ApplyBeginDate, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.ApplyBeginDate, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.ApplyEndDate, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.ApplyEndDate, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.ApplyEndDate, "", new { @class = "text-danger" })
		</div>
	</div>

	@*<div class="form-group">
		@Html.LabelFor(model => model.CanSold, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.CanSold, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "1" } })
			@Html.ValidationMessageFor(model => model.CanSold, "", new { @class = "text-danger" })
		</div>
	</div>*@

	<div class="form-group">
		@Html.LabelFor(model => model.TotalNum, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.TotalNum, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "1" } })
			@Html.ValidationMessageFor(model => model.TotalNum, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })*@
			<input type="file" name="ImageFile" id="ImageFile" onchange="validateFileAndPreview();" />
			@Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		<img id="imagePreview" alt="Image Preview" />
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@*@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })*@
			<input type="file" name="DescriptionFile" id="DescriptionFile" onchange="validateFile();" />
			@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
		</div>
	</div>

	<!--<div class="form-group">
		@Html.LabelFor(model => model.Alert, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">-->
	@*@Html.EditorFor(model => model.Alert, new { htmlAttributes = new { @class = "form-control" } })*@
	<!--<input type="file" name="AlertFile" id="AlertFile" onchange="validateFile();" />
			@Html.ValidationMessageFor(model => model.Alert, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.PriceDescription, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">-->
	@*@Html.EditorFor(model => model.PriceDescription, new { htmlAttributes = new { @class = "form-control" } })*@
	<!--<input type="file" name="PriceDescriptionFile" id="PriceDescriptionFile" onchange="validateFile();" />
			@Html.ValidationMessageFor(model => model.PriceDescription, "", new { @class = "text-danger" })
		</div>
	</div>-->

	<div class="col-md-6">
		<button type="submit" class="btn btn-primary">
			<i class="fas fa-save"></i> 存檔
		</button>
		<a href="@Url.Action("Index")" class="btn btn-dark">
			<i class="fas fa-arrow-circle-left"></i> 返回
		</a>
	</div>
</div>
}

@section Scripts {
	<script>
		function previewImage() {
			var fileInput = document.getElementById('ImageFile');
			var imagePreview = document.getElementById('imagePreview');

			if (fileInput.files && fileInput.files[0]) {
				var reader = new FileReader();

				reader.onload = function (e) {
					if (e.target.result !== null && e.target.result !== "") {
						imagePreview.src = e.target.result;
					} else {
						// 如果 URL 為空，不顯示圖片
						imagePreview.src = "";
					}
				}

				reader.readAsDataURL(fileInput.files[0]);
			} else {
				// 如果未選擇檔案，不顯示圖片
				imagePreview.src = "";
			}
		}
		function validateFileSelect() {
			var imagePreview = document.getElementById('imagePreview');
			var fileInput_PriceDescriptionFile = document.getElementById('PriceDescriptionFile');
			var fileInput_AlertFile = document.getElementById('AlertFile');
			var fileInput_DescriptionFile = document.getElementById('DescriptionFile');
			if (imagePreview.src == "" || fileInput_PriceDescriptionFile.files.length == 0 || fileInput_AlertFile.files.length == 0 || fileInput_DescriptionFile.files.length == 0) {
				// 如果未選擇檔案，顯示警告並阻止提交表單
				alert("請選擇要上傳的圖片跟檔案！");
				return false;
			}

			// 如果已選擇檔案，可以提交表單
			return true;
		}
		function validateFileAndPreview() {
			var allowedTypes = ['image/jpeg', 'image/png'];
			var fileInput = document.getElementById('ImageFile');
			var filePath = fileInput.value;
			var fileType = fileInput.files[0].type;

			if (allowedTypes.indexOf(fileType) === -1) {
				alert('僅支持 jpg 和 png 格式的圖片');
				// 清空文件選擇框，避免用戶上傳錯誤格式的文件
				fileInput.value = '';
			} else {
				// 如果檔案類型通過驗證，則調用 previewImage 函數
				previewImage();
			}
		}
		function validateFile() {
			var allowedTypes = ['application/pdf'];

			/*var fileInput_PriceDescriptionFile = document.getElementById('PriceDescriptionFile');
			var fileInput_AlertFile = document.getElementById('AlertFile');*/
			var fileInput_DescriptionFile = document.getElementById('DescriptionFile');

			/*
			if (fileInput_PriceDescriptionFile.files.length > 0) {
				var fileType_PriceDescriptionFile = fileInput_PriceDescriptionFile.files[0].type;
				if (allowedTypes.indexOf(fileType_PriceDescriptionFile) === -1) {
					alert('僅可上傳pdf檔');
					// 清空文件選擇框，避免用戶上傳錯誤格式的文件
					fileInput_PriceDescriptionFile.value = '';
				}
			}
			
			if (fileInput_AlertFile.files.length > 0) {
				var fileType_AlertFile = fileInput_AlertFile.files[0].type;

				if (allowedTypes.indexOf(fileType_AlertFile) === -1) {
					alert('僅可上傳pdf檔');
					// 清空文件選擇框，避免用戶上傳錯誤格式的文件
					fileInput_AlertFile.value = '';
				}
			}*/
			if (fileInput_DescriptionFile.files.length > 0) {
				var fileType_DescriptionFile = fileInput_DescriptionFile.files[0].type;

				if (allowedTypes.indexOf(fileType_DescriptionFile) === -1) {
					alert('僅可上傳pdf檔');
					// 清空文件選擇框，避免用戶上傳錯誤格式的文件
					fileInput_DescriptionFile.value = '';
				}
			}
		}
	</script>
	@Scripts.Render("~/bundles/jqueryval")
}

Team1/Views/Package/Edit.cshtml
@model Team1.ViewModels.PackageVM

@{
	ViewBag.Title = "Edit";
}

<style>
	h2 {
		background-color: powderblue;
		padding: 10px;
	}

	.form-horizontal {
		width: 80%;
		margin: auto;
	}

	.control-label {
		font-weight: bold;
	}

	.form-group {
		margin-bottom: 15px;
	}

	.col-md-offset-2 {
		margin-left: 16.66666667%;
	}

	.btn {
		margin-top: 15px;
	}

	#imagePreview {
		max-width: 100%;
		max-height: 200px;
		margin-top: 10px;
	}

	.form-group {
		width: 500px
	}
	.readonly-input {
		background-color: #f0f0f0; /* 這裡是你想要的底色 */
	}

</style>

<h2>產品設定-修改</h2>

@using (Html.BeginForm("Edit", "Package", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return validateFileSelect();" }))
{
	@Html.AntiForgeryToken()

<div class="form-horizontal">
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control readonly-input", @readonly = "readonly" } })
			@Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
			@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.LowestGo, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.LowestGo, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "1" } })
			@Html.ValidationMessageFor(model => model.LowestGo, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.ApplyBeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.ApplyBeginDate, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.ApplyBeginDate, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.ApplyEndDate, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.ApplyEndDate, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.ApplyEndDate, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.TotalNum, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.TotalNum, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "1" } })
			@Html.ValidationMessageFor(model => model.TotalNum, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })*@
			<input type="file" name="ImageFile" id="ImageFile" onchange="validateFileAndPreview();" />
			@Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		<img id="imagePreview" alt="Image Preview"src="@Url.Content(Model.Image)" />
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			<a href="javascript:void(0);" onclick="openPDF('@Url.Content(Model.Description)')">View PDF</a>
			<br/>
			<input type="file" name="DescriptionFile" id="DescriptionFile" onchange="validateFile();" />
			@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="col-md-6">
		<button type="submit" class="btn btn-primary">
			<i class="fas fa-save"></i> 存檔
		</button>
		<a href="@Url.Action("Index")" class="btn btn-dark">
			<i class="fas fa-arrow-circle-left"></i> 返回
		</a>
	</div>
</div>
}

@section Scripts {
	<script>
		function previewImage() {
			var fileInput = document.getElementById('ImageFile');
			var imagePreview = document.getElementById('imagePreview');

			if (fileInput.files && fileInput.files[0]) {
				var reader = new FileReader();

				reader.onload = function (e) {
					if (e.target.result !== null && e.target.result !== "") {
						imagePreview.src = e.target.result;
					} else {
						// 如果 URL 為空，不顯示圖片
						imagePreview.src = "";
					}
				}

				reader.readAsDataURL(fileInput.files[0]);
			} else {
				// 如果未選擇檔案，不顯示圖片
				imagePreview.src = "";
			}
		}
		function validateFileSelect() {
			var imagePreview = document.getElementById('imagePreview');
			var fileInput_PriceDescriptionFile = document.getElementById('PriceDescriptionFile');
			var fileInput_AlertFile = document.getElementById('AlertFile');
			var fileInput_DescriptionFile = document.getElementById('DescriptionFile');
			if (imagePreview.src == "" || fileInput_PriceDescriptionFile.files.length == 0 || fileInput_AlertFile.files.length == 0 || fileInput_DescriptionFile.files.length == 0) {
				// 如果未選擇檔案，顯示警告並阻止提交表單
				alert("請選擇要上傳的圖片跟檔案！");
				return false;
			}

			// 如果已選擇檔案，可以提交表單
			return true;
		}
		function validateFileAndPreview() {
			var allowedTypes = ['image/jpeg', 'image/png'];
			var fileInput = document.getElementById('ImageFile');
			var filePath = fileInput.value;
			var fileType = fileInput.files[0].type;

			if (allowedTypes.indexOf(fileType) === -1) {
				alert('僅支持 jpg 和 png 格式的圖片');
				// 清空文件選擇框，避免用戶上傳錯誤格式的文件
				fileInput.value = '';
			} else {
				// 如果檔案類型通過驗證，則調用 previewImage 函數
				previewImage();
			}
		}
		function validateFile() {
			var allowedTypes = ['application/pdf'];

			/*var fileInput_PriceDescriptionFile = document.getElementById('PriceDescriptionFile');
			var fileInput_AlertFile = document.getElementById('AlertFile');*/
			var fileInput_DescriptionFile = document.getElementById('DescriptionFile');

			/*
			if (fileInput_PriceDescriptionFile.files.length > 0) {
				var fileType_PriceDescriptionFile = fileInput_PriceDescriptionFile.files[0].type;
				if (allowedTypes.indexOf(fileType_PriceDescriptionFile) === -1) {
					alert('僅可上傳pdf檔');
					// 清空文件選擇框，避免用戶上傳錯誤格式的文件
					fileInput_PriceDescriptionFile.value = '';
				}
			}

			if (fileInput_AlertFile.files.length > 0) {
				var fileType_AlertFile = fileInput_AlertFile.files[0].type;

				if (allowedTypes.indexOf(fileType_AlertFile) === -1) {
					alert('僅可上傳pdf檔');
					// 清空文件選擇框，避免用戶上傳錯誤格式的文件
					fileInput_AlertFile.value = '';
				}
			}*/
			if (fileInput_DescriptionFile.files.length > 0) {
				var fileType_DescriptionFile = fileInput_DescriptionFile.files[0].type;

				if (allowedTypes.indexOf(fileType_DescriptionFile) === -1) {
					alert('僅可上傳pdf檔');
					// 清空文件選擇框，避免用戶上傳錯誤格式的文件
					fileInput_DescriptionFile.value = '';
				}
			}
		}
		function openPDF(url) {
			window.open(url, '_blank', 'height=600,width=800');
		}
	</script>
	@Scripts.Render("~/bundles/jqueryval")
}